name: Download Reports 2
# on: [push, workflow_dispatch]
on: [workflow_dispatch]

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pandas openpyxl xlrd gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client packaging
    
    - name: Download Comiss√µes Report
      env:
        SGF_USERNAME: ${{ secrets.SGF_USERNAME }}
        SGF_PASSWORD: ${{ secrets.SGF_PASSWORD }}
      run: python scrt/comissao_vendedor.py

    - name: Update COMISSOES Worksheet
      env:
        GSA_CREDENTIALS: ${{ secrets.CRAPPY_CREDENTIALS }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
      run: python scrt/proc/ready_comissao_vendedor.py
      
    - name: Download Vendas por Vendedor Report
      env:
        SGF_USERNAME: ${{ secrets.SGF_USERNAME }}
        SGF_PASSWORD: ${{ secrets.SGF_PASSWORD }}
      run: python scrt/venda_vendedor.py

    - name: Update VENDAS_VENDEDOR Worksheet
      env:
        GSA_CREDENTIALS: ${{ secrets.CRAPPY_CREDENTIALS }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
      run: python scrt/proc/ready_venda_vendedor.py

    - name: Download Venda Filial Report
      env:
        SGF_USERNAME: ${{ secrets.SGF_USERNAME }}
        SGF_PASSWORD: ${{ secrets.SGF_PASSWORD }}
      run: python scrt/venda_filial.py

    - name: Update VENDAS_FILIAL Worksheet
      env:
        GSA_CREDENTIALS: ${{ secrets.CRAPPY_CREDENTIALS }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
      run: python scrt/proc/ready_venda_filial.py
