name: Download Reports
# on: [push, workflow_dispatch]
on: [workflow_dispatch]

jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pandas openpyxl xlrd gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client packaging
    
    - name: Download Trier Report
      env:
        SGF_USERNAME: ${{ secrets.SGF_USERNAME }}
        SGF_PASSWORD: ${{ secrets.SGF_PASSWORD }}
      run: python scrt/user_trier.py

    - name: Download SCI Report
      env:
        SCI_USERNAME: ${{ secrets.SCI_USERNAME }}
        SCI_PASSWORD: ${{ secrets.SCI_PASSWORD }}
      run: python scrt/user_sci.py

    - name: Update user_trier Worksheet
      env:
        GSA_CREDENTIALS: ${{ secrets.CRAPPY_CREDENTIALS }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
      run: python scrt/proc/ready_user_trier.py

    - name: Update user_sci Worksheet
      env:
        GSA_CREDENTIALS: ${{ secrets.CRAPPY_CREDENTIALS }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
      run: python scrt/proc/ready_user_sci.py

    - name: Update filtered_user Worksheet
      env:
        GSA_CREDENTIALS: ${{ secrets.CRAPPY_CREDENTIALS }}
        SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
      run: python scrt/calc/user_calc.py
